language: python
python:
  - "3.5.2"
# command to run tests
install:
  - pip install -r requirements.txt
script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test
  
after_success:  
  - coveralls